#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -cp "$APPDIR/src:$APPDIR/bin:/Users/fongcn/tools/gwt-mac-1.4.61/gwt-user.jar:/Users/fongcn/tools/gwt-mac-1.4.61/gwt-dev-mac.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" com.gwtsite.FileUploader/FileUploader.html;
